// Generated by CoffeeScript 1.10.0

/*
 * service-checker : lib/errors/ExitError
 * Author: MrKMG (https://github.com/mrkmg)
 *
 * MIT License
 */


/* istanbul ignore next */

(function() {
  var DuplicateProviderError,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  DuplicateProviderError = (function(superClass) {
    extend(DuplicateProviderError, superClass);

    DuplicateProviderError.prototype.message = 'Duplicate Plugin Provider';

    DuplicateProviderError.prototype.provider = 'other';

    function DuplicateProviderError(provider) {
      this.provider = provider;
      this.message = this.provider + " is already a registered plugin";
    }

    return DuplicateProviderError;

  })(Error);

  module.exports = DuplicateProviderError;

}).call(this);
