// Generated by CoffeeScript 1.10.0

/*
 * service-checker : lib/errors/ExitError
 * Author: MrKMG (https://github.com/mrkmg)
 *
 * MIT License
 */


/* istanbul ignore next */

(function() {
  var ExitError,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  ExitError = (function(superClass) {
    extend(ExitError, superClass);

    ExitError.prototype.message = 'Exit Error';

    ExitError.prototype.code = 255;

    function ExitError(code, message) {
      this.code = code;
      this.message = message;
    }

    return ExitError;

  })(Error);

  module.exports = ExitError;

}).call(this);
