// Generated by CoffeeScript 1.10.0

/*
 * service-checker : lib/errors/UsageError
 * Author: MrKMG (https://github.com/mrkmg)
 *
 * MIT License
 */


/* istanbul ignore next */

(function() {
  var UsageError,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  UsageError = (function(superClass) {
    extend(UsageError, superClass);

    UsageError.prototype.message = 'Show The Usage';

    function UsageError() {}

    return UsageError;

  })(Error);

  module.exports = UsageError;

}).call(this);
