// Generated by CoffeeScript 1.10.0

/*
 * server-checker : test/fixtures/dns/valid
 * Author: MrKMG (https://github.com/mrkmg)
 *
 * MIT License
 */

(function() {
  var dns;

  dns = require('native-dns');

  module.exports = function() {
    var server;
    server = dns.createServer();
    server.on('request', function(request, response) {
      response.answer.push(dns.A({
        name: request.question[0].name,
        address: '127.0.0.1',
        ttl: 600
      }));
      return response.send();
    });
    return {
      start: function(port, callback) {
        server.on('listening', callback);
        return server.serve(port);
      },
      stop: function(callback) {
        server.on('close', callback);
        return server.close();
      }
    };
  };

}).call(this);
