// Generated by CoffeeScript 1.10.0
(function() {
  var http, ping, rawTcp, serviceChecker, smtp;

  serviceChecker = require('./lib/service-checker');

  http = require('./lib/plugins/http');

  smtp = require('./lib/plugins/smtp');

  ping = require('./lib/plugins/ping');

  rawTcp = require('./lib/plugins/raw-tcp');

  module.exports = function(options) {
    var instance;
    instance = serviceChecker(options);
    instance.use(http);
    instance.use(smtp);
    instance.use(ping);
    instance.use(rawTcp);
    return instance;
  };

}).call(this);
