// Generated by CoffeeScript 1.10.0
(function() {
  var dns, http, ping, rawTcp, serviceChecker, smtp;

  serviceChecker = require('./lib/service-checker');

  http = require('./lib/plugins/http');

  smtp = require('./lib/plugins/smtp');

  ping = require('./lib/plugins/ping');

  rawTcp = require('./lib/plugins/raw-tcp');

  dns = require('./lib/plugins/dns');

  module.exports = function(options) {
    var instance;
    instance = serviceChecker(options);
    instance.use(http).use(smtp).use(ping).use(rawTcp).use(dns);
    return instance;
  };

}).call(this);
