// Generated by CoffeeScript 1.10.0
(function() {
  'use strict';

  /**
   * server-checker : test/specs/main/init
   * Author: MrKMG (https://github.com/mrkmg)
   *
   * MIT License
   */
  var assert, chai, serviceChecker;

  chai = require('chai');

  chai.use(require('chai-as-promised'));

  assert = chai.assert;

  serviceChecker = require('../../..')();

  describe('MAIN: Module Exists', function() {
    return it("_name should exist and equal 'service-checker'", function() {
      return assert.equal(serviceChecker._name, 'service-checker');
    });
  });

}).call(this);
