// Generated by CoffeeScript 1.10.0

/*
 * server-checker : test/fixtures/smtp/server-valid
 * Author: MrKMG (https://github.com/mrkmg)
 *
 * MIT License
 */

(function() {
  var SMTPServer, _;

  SMTPServer = require('smtp-server').SMTPServer;

  _ = require('underscore');

  module.exports = function() {
    var client;
    client = new SMTPServer({
      secure: false,
      logger: false,
      hideSTARTTLS: true
    });
    return {
      start: function(port, callback) {
        return client.listen(port, 'localhost', callback);
      },
      stop: function(callback) {
        if (!_.isFunction(callback)) {
          callback = _.noop;
        }
        return client.close(callback);
      }
    };
  };

}).call(this);
