// Generated by CoffeeScript 1.10.0

/*
 * server-checker : test/specs/main/plugin
 * Author: MrKMG (https://github.com/mrkmg)
 *
 * MIT License
 */

(function() {
  var assert, chai, serviceChecker;

  chai = require('chai');

  chai.use(require('chai-as-promised'));

  assert = chai.assert;

  serviceChecker = require('../../..')();

  describe('MAIN: plugin system', function() {
    it('should have a use function', function() {
      assert.property(serviceChecker, 'use');
      return assert.isFunction(serviceChecker.use);
    });
    it('should throw if plugin is not an object (name: handler)', function() {
      return assert["throw"](function() {
        return serviceChecker.use('');
      });
    });
    return it('should throw if plugin does not have a valid schema', function() {
      return assert["throw"](function() {
        return serviceChecker.use({
          badPlugin: true
        });
      });
    });
  });

}).call(this);
