// Generated by CoffeeScript 1.10.0

/*
 * server-checker : test/specs/plugins/dns
 * Author: MrKMG (https://github.com/mrkmg)
 *
 * MIT License
 */

(function() {
  var assert, async, chai, serviceChecker;

  chai = require('chai');

  chai.use(require('chai-as-promised'));

  assert = chai.assert;

  async = require('async');

  serviceChecker = require('../../..')({
    timeout: 1000
  });

  describe('PLUGIN: dns', function() {
    var server_valid;
    server_valid = require('../../fixtures/dns/valid')();
    before('starting up test servers', function(done) {
      return async.parallel([
        function(callback) {
          return server_valid.start(10000, callback);
        }
      ], done);
    });
    after('closing test servers', function(done) {
      return async.parallel([
        function(callback) {
          return server_valid.stop(callback);
        }
      ], done);
    });
    it('should have method', function() {
      return assert.property(serviceChecker, 'dns');
    });
    it('should return success:true for valid request', function() {
      var options;
      options = {
        host: '127.0.0.1',
        port: 10000
      };
      return assert.eventually.include(serviceChecker.dns(options), {
        success: true
      });
    });
    return it('should return success:false for timeout', function() {
      var options;
      options = {
        host: '127.0.0.1',
        port: 10001
      };
      return assert.eventually.include(serviceChecker.dns(options), {
        success: false
      });
    });
  });

}).call(this);
