// Generated by CoffeeScript 1.10.0

/*
 * service-checker
 * Author: MrKMG (https://github.com/mrkmg)
 * Inspired from https://github.com/stevenzeiler/promise-while/blob/75e6aefc9c891012cac7cb76a1b3f04f699ca3d7/index.js
 *
 * MIT License
 */

(function() {
  var PromiseWhile;

  PromiseWhile = function(Promise) {
    return function(condition, action) {
      return new Promise(function(resolve, reject) {
        var last_result, whileLoop;
        last_result = void 0;
        whileLoop = function() {
          return Promise["try"](function() {
            return action(last_result);
          }).then(function(action_result) {
            return last_result = action_result;
          }).then(condition).then(function(test_result) {
            if (test_result) {
              return whileLoop();
            } else {
              return resolve(last_result);
            }
          })["catch"](reject);
        };
        return whileLoop();
      });
    };
  };

  module.exports = PromiseWhile;

}).call(this);
